version: "3"

services:
  lantern:
    build: ./
    image: lantern
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  test:
    image: lantern
    command: ./test/extension-count.sh
    volumes:
      - ./test:/test
    depends_on:
      lantern:
        condition: service_healthy