version: "3"

services:
  postgres:
    build: ./
    ports:
      - "5432:5432"
      - "6432:6432"
    volumes:
      - "pg-data:/var/lib/postgresql/data"
      - "pg-socket-dir:/var/run/postgresql"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  cli:
    image: lanterndata/lantern-cli:0.1.15-cpu
    ports:
      - "8080:8080"
    volumes:
      - "pg-socket-dir:/var/run/postgresql"
      - "pg-data:/var/lib/postgresql/data"
    command: "start-server --host 0.0.0.0 --port 8080 --db-uri 'postgres://postgres@%2Fvar%2Frun%2Fpostgresql/postgres'"
    depends_on:
      postgres:
        condition: service_healthy

  elastic:
    image: elasticsearch:8.13.4
    volumes:
      - "elastic-data:/usr/share/elasticsearch/data"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
      - 9300:9300

volumes:
  pg-data:
    driver: local
  pg-socket-dir:
    driver: local
  elastic-data:
    driver: local
