name: publish
on:
  push:
    branches:
      - main
env:
  VERSION: "0.1.16"
  IMAGE_NAME: "lanterndata/lantern-suite"
  LANTERN_VERSION: "0.2.5"
  LANTERN_EXTRAS_VERSION: "0.1.4"
  PG_CRON_VERSION: "7e91e72b1bebc5869bb900d9253cc9e92518b33f"
jobs:
  docker:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - postgres: 16
          - postgres: 15
          - postgres: 14
          - postgres: 13
          - postgres: 12
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            PG_VERSION=${{ matrix.postgres }}
            LANTERN_VERSION=${{ env.LANTERN_VERSION }}
            LANTERN_EXTRAS_VERSION=${{ env.LANTERN_EXTRAS_VERSION }}
            PG_CRON_VERSION=${{ env.PG_CRON_VERSION }}
          tags: |
            ${{ env.IMAGE_NAME }}:pg${{ matrix.postgres }}-latest
            ${{ env.IMAGE_NAME }}:pg${{ matrix.postgres }}-v${{ env.VERSION }}