name: Run Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build Docker image without cache
      run: docker build --no-cache -t lantern-test .
    - name: Run the container
      run: docker run --rm -v ${{ github.workspace }}/test:/test -e POSTGRES_HOST_AUTH_METHOD=trust -d --name lantern-test-container lantern-test
    - name: Run tests
      run: docker exec lantern-test-container bash -c "/test/run-all.sh || exit 1"